### ISSUE TITLE
Repo code giving errors after download

### ISSUE THREAD

**Issue by Ijaz-Tufail** [gazugafan/fingerpass#4]
Hi,
Can you please give the error free code of this project. And I need to use laptop's fingerprint scanner's data to save and verify. Please can you suggest how can I achieve this.

My requirements are:
- Save an employee's finger data (taken from system's built in fingerprint scanner) along with other data to database
- access and verify that employee
- take picture (snapshot) of employee's with camera

**Comment by gazugafan** [comment]
This is not an issue

**Comment by Ijaz-Tufail** [comment]
But I can't build/run this repo code on my machine it gives errors. Can you help in this?

**Comment by gazugafan** [comment]
Possibly. What are the errors?
